kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-backend-canary
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        component: demo-backend
        app: demo
        role: backend
        env: canary
    spec:
      containers:
      - name: backend
        image: gcr.io/gke-travisci-deployment/demo-backend:1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always