kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-backend-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      role: backend
      env: canary
  template:
    metadata:
      name: backend
      labels:
        app: demo
        role: backend
        env: canary
    spec:
      containers:
      - name: backend
        image: gcr.io/gke-travisci-deployment/demo-backend:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        ports:
          - name: backend
            containerPort: 8080