apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      role: backend
      env: production
  template:
    metadata:
      name: backend
      labels:
        app: demo
        role: backend
        env: dev
    spec:
      containers:
        - name: demo-api
          image: gcr.io/gke-travisci-deployment/demo-backend:1.0.0
          ports:
            - containerPort: 8080
