apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      role: frontend
      env: production
  template:
    metadata:
      labels:
        app: demo
        role: frontend
        env: production
    spec:
      containers:
        - name: demo-frontend
          image: gcr.io/gke-travisci-deployment/demo-frontend:1.0.0
          ports:
            - containerPort: 4200