kind: Service
apiVersion: v1
metadata:
  name: demo-frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 4200
    protocol: TCP
  selector:
    app: demo
    role: frontend